### PR TITLE
Fix tags from allowing duplicates with different cases

### LINKED ISSUE #162: [PE-D] Handling of repeated tags
Currently, users can continue to add tags even though the same tag already exist. 
It may be better if repeated tags are not allowed to be added.
For example, tag Photoshop can be continued to add even though it has already been present for all persons.

Before:

After:

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: litone01/ped#16

### LINKED ISSUE #189: [PE-D] Tags allow duplicates
Tags do not check if it is caps lock or not.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: kieron560/ped#3

### LINKED ISSUE #193: [PE-D] Tag Delete allows me to delete non-existent tags
No details provided.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: kieron560/ped#7

### PR DESCRIPTION
**Pull request by tanboonji**
- Changed `.hashCode()` in `Tag` to allow `Tag` to be checked while ignoring case
- Updated test cases to check if tags with the same name but different case have the same identity
- Updated command output for `TagCommand`
- Updated DG for `TagCommand`

Fixes #162 
Fixes #189 
Fixes #193

Netlfiy deploy preview: https://deploy-preview-244--a-bash-book.netlify.app/

### CODE REVIEW

**Comment by justgnohUG** [comment]
The solution works. However, system message can be quite confusing. If it shows added first, then the disclaimer on duplicates.

A possible workaround I would suggest is to have the Note above the System message.

image

**Comment by tanboonji** [comment]
> The solution works. However, system message can be quite confusing. If it shows added first, then the disclaimer on duplicates.
> 
> A possible workaround I would suggest is to have the Note above the System message.
> 
> image

I feel that the command result should always be the first line because that is the most important feedback message from the command.

I have changed the note in the command result, is it clearer now?

image

**Review by yaowei-soc — APPROVED** [review]
Feature works perfectly. However the documentation may not be sufficient to explain the intricacies of the tag feature (IMO, some users reading this may be confused by how the feature works).

**Review by justgnohUG — APPROVED** [review]
Command Result is much clearer now. 

LGTM

**Review by darkdestry-t — APPROVED** [review]
Reviewed non documentation changes and it looks good. LGTM

**Review by darkdestry-t — APPROVED** [review]

**Review by oeiyiping — COMMENTED** [review]
LGTM aside from minor consistency issue:

image
In the "Note" section, might want to change persons -> person(s) to stay consistent with the line above it.

**Review by oeiyiping — APPROVED** [review]
LGTM.

**Pull request merged**
