### PR TITLE
Update FilterCommand messages

### LINKED ISSUE #153: [PE-D] Filter command: invalid field prefixes are not handled
This is similar but different from the issue of field prefixes in edit command.

`filter - a` (there is a space between '-' and 'a')
should be treated as invalid, but can be successfully applied.

Before:

After:

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: litone01/ped#7

### PR DESCRIPTION
**Pull request by yaowei-soc**
Closes #153 

Updated messages:

| Command         | Message                          |
| --------------- | -------------------------------- |
| `filter`        | Removed filter                   |
| `filter 123`    | Invalid prefix provided '123'    |
| `filter -a`     | Applied filter -a                |
| `filter -a -s`  | Invalid prefix provided '-a-s'   |
| `filter -aasdf` | Invalid prefix provided '-aasdf' |
| `filter -s`     | Invalid prefix provided '-s'     |

Possible dependency on #234 due to the parsing of prefixes

> Example of issue:
> Implementation **with no spaces**
> 
> | Command           | Message                          |
> | ----------------- | -------------------------------- |
> | `filter -nap`     | Invalid prefix provided '-nap'   |
> | `filter -n ap`    | Invalid prefix provided '-nap'   |
> | `filter -n -q -j` | Invalid prefix provided '-n-q'   |
> | `filter -n-q -j`  | Invalid prefix provided '-n-q'   |
> | `filter -nasdf`   | Invalid prefix provided '-nasdf' |
> 
> 
> Implementation **with spaces**
> 
> | Command           | Message                           |
> | ----------------- | --------------------------------- |
> | `filter -nap`     | Invalid prefix provided '-n ap'   |
> | `filter -n ap`    | Invalid prefix provided '-n ap'   |
> | `filter -n -q -j` | Invalid prefix provided '-n -q'   |
> | `filter -n-q -j`  | Invalid prefix provided '-n -q'   |
> | `filter -nasdf`   | Invalid prefix provided '-n asdf' |

> There is no way of me differentiating between `-n ap` and `-nap` via ArgumentMultimap

Updated message
| Command               | Message                            |
| --------------------- | ---------------------------------- |
| `filter -nap`         | Invalid prefix near '-nap'         |
| `filter -n ap`        | Invalid prefix near '-n ap'        |
| `filter -n -q -j`     | Invalid prefix near '-n -q -j'     |
| `filter -n-q -j`      | Invalid prefix near '-n-q -j'      |
| `filter -nasdf`       | Invalid prefix near '-nasdf'       |
| `filter -nasdf -p -a` | Invalid prefix near '-nasdf -p -a' |
| `filter -p -a -asdf`  | Invalid prefix near '-a -asdf'     |
| `filter -p -a`        | Applied filter '-p -a'             |

### CODE REVIEW

**Review by oeiyiping — COMMENTED** [review]
image

If the invalid prefix starts with a valid prefix, the return message returns the invalid prefix excluding the valid portion. Aside from this, everything is working as intended.

**Comment by yaowei-soc** [comment]
@oeiyiping 
image

Updated to show the full invalid prefix

**Review by tanboonji — CHANGES_REQUESTED** [review]
Error message `Invalid prefix provided '-n-q'` does not have space between `-n` and `-q` when I execute `filter -n -q -j` command.

image

**Review by oeiyiping — APPROVED** [review]
LGTM.

Just a minor comment:
"Invalid prefix near (substring)" might seem confusing at first glance, unless it is properly explained what this message means in the UG.

**Review by tanboonji — APPROVED** [review]
LGTM

**Pull request merged**
