### PR TITLE
docs: Add personal portfolio page draft

### PR DESCRIPTION
**Pull request by justgnohUG**
In partial completion of #206

### CODE REVIEW

**Review by oeiyiping — APPROVED** [review]
LGTM. Just a note:  This is just a draft, but remember to add in your PPP link in AboutUs.md before the actual submission.

**Comment by darkdestry-t** [comment]
Note that your file name is not lower case.
image

**Review by yaowei-soc — CHANGES_REQUESTED** [review]
Need to add to AboutUs.md

**Review by yaowei-soc — APPROVED** [review]
LGTM

**Pull request merged**
