### PR TITLE
Fix help menu

### LINKED ISSUE #156: [PE-D] Help command and UI: unable to view the end of help page after adjusting window size.
Unable to see several parts of the help page when the window size is reduced. It is more severe when reducing the width. More details can be found in the video and screenshots.

Screenshots:

Video:
[p88BTBr1k8.mp4](https://raw.githubusercontent.com/litone01/ped/main/files/fd678ebb-6175-42bc-8eac-1a9dabf33f18.mp4)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: litone01/ped#10

### LINKED ISSUE #166: [PE-D] "Help" window resolution is too large
When I typed "help", the user guide window appeared but it was too large (Unable to see the close/minimise buttons). 

Screenshot:

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: laurenlhy/ped#2

### LINKED ISSUE #187: [PE-D] Help Window Size Issue
Help Window when resized to a very small size, though it can scroll up and down, it cannot be scrolled left or right, causing the words to get cut off.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: kieron560/ped#1

### LINKED ISSUE #194: [PE-D] Links in Help Window buggy
Expected links in Help Window to direct me to the site in my browser, but it instead redirects in the help window, which causes view issues.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: kieron560/ped#8

### LINKED ISSUE #214: Fix help menu in whole
Fix help menu to not rely on web services:
- #194 

Fix help menu window size issues:
- #156 
- #166 
- #187

### PR DESCRIPTION
**Pull request by oeiyiping**
Notable changes:
- Changed implementation from rendering html to parsing UserGuide.md and displaying command summary as text.
- Removed dependencies on javafx webview and media from gradle.build.

Related issues:
  - Resolves #214
  - Resolves #194 
  - Resolves #156 
  - Resolves #166
  - Resolves #187

### CODE REVIEW

**Comment by yaowei-soc** [comment]
This solution works, however I'm not too keen on the idea of duplicating a `UserGuide.md` to achieve the help command. Perhaps the team can chime in on the possible implementations?

One solution that I can think of is to prevent the WebEngine from loading Github links (we can see from #194 that loading Github links do not work properly)

So we can prevent the WebEngine from loading links by doing something like this:

```java
WebEngine engine = webview.getEngine();
engine.locationProperty().addListener((observable, oldValue, newValue) -> {
    if (newValue.contains("badsite")) { // replace with your URL checking logic
        Platform.runLater(() -> {
            // Load your block page url
            engine.load("http://example.com"));
        }
    }
});
```

Reference:

- https://stackoverflow.com/questions/34377282/how-to-deny-access-to-webpage-from-javafx-web
- https://stackoverflow.com/questions/15555510/javafx-stop-opening-url-in-webview-open-in-browser-instead

**Comment by oeiyiping** [comment]
> This solution works, however I'm not too keen on the idea of duplicating a `UserGuide.md` to achieve the help command. Perhaps the team can chime in on the possible implementations?
> 
> One solution that I can think of is to prevent the WebEngine from loading Github links (we can see from #194 that loading Github links do not work properly)
> 
> So we can prevent the WebEngine from loading links by doing something like this:
> 
> ```java
> WebEngine engine = webview.getEngine();
> engine.locationProperty().addListener((observable, oldValue, newValue) -> {
>     if (newValue.contains("badsite")) { // replace with your URL checking logic
>         Platform.runLater(() -> {
>             // Load your block page url
>             engine.load("http://example.com"));
>         }
>     }
> });
> ```
> 
> Reference:
> 
> * https://stackoverflow.com/questions/34377282/how-to-deny-access-to-webpage-from-javafx-web
> * https://stackoverflow.com/questions/15555510/javafx-stop-opening-url-in-webview-open-in-browser-instead

Yeah I understand, personally don't like having to duplicate files and needing to maintain both. 
One reason I eventually went with this solution is that it does not require internet access at all. Back in 1.3, I was already intending to include a copy of UserGuide.html in the resource folder just to avoid having to rely on an active internet connection.  After considering the html rendering issues, I eventually chose to use the current implementation, which only relies on parsing and printing text, and can be completed within the milestone. 

Of course if anyone has a better alternative that can be completed within the milestone, please do share.

**Comment by tanboonji** [comment]
I personally feel that there isn't a need to copy the whole `UserGuide.md` over. Here are some of my thoughts on the implementation:

1) If we were to use the whole `UserGuide.md` and extract out only the command summary table, then I feel there isn't a point for the rest of the `UserGuide.md` to be copied over to resources.
2) If we were to copy the whole `UserGuide.md`, would that mean that I would need to update the copy even though the command summary table is not updated?
3) The help window only requires the command summary table, which would not be updated frequently unless there are implementation changes to commands. With that consideration, personally, I feel that hard coding the command summary table in the help window would suffice.
4) It is possible to better format the command summary table in the help window? For example, to use a table, because the command summary table now is not very organised and hard to read.
5) I would strongly suggest against using anything that has to deal with network connectivity and using the WebEngine to display the help window.

**Comment by tanboonji** [comment]
I personally feel that there isn't a need to copy the whole `UserGuide.md` over. Here are some of my thoughts on the implementation:

1) If we were to use the whole `UserGuide.md` and extract out only the command summary table, then I feel there isn't a point for the rest of the `UserGuide.md` to be copied over to resources.
2) If we were to copy the whole `UserGuide.md`, would that mean that I would need to update the copy even though the command summary table is not updated?
3) The help window only requires the command summary table, which would not be updated frequently unless there are implementation changes to commands. With that consideration, personally, I feel that hard coding the command summary table in the help window would suffice.
4) It is possible to better format the command summary table in the help window? For example, to use a table, because the command summary table now is not very organised and hard to read.
5) I would strongly suggest against using anything that has to deal with network connectivity and using the WebEngine to display the help window.

**Comment by oeiyiping** [comment]
> I personally feel that there isn't a need to copy the whole `UserGuide.md` over. Here are some of my thoughts on the implementation:
> 
> 1. If we were to use the whole `UserGuide.md` and extract out only the command summary table, then I feel there isn't a point for the rest of the `UserGuide.md` to be copied over to resources.
> 2. If we were to copy the whole `UserGuide.md`, would that mean that I would need to update the copy even though the command summary table is not updated?
> 3. The help window only requires the command summary table, which would not be updated frequently unless there are implementation changes to commands. With that consideration, personally, I feel that hard coding the command summary table in the help window would suffice.
> 4. It is possible to better format the command summary table in the help window? For example, to use a table, because the command summary table now is not very organised and hard to read.
> 5. I would strongly suggest against using anything that has to deal with network connectivity and using the WebEngine to display the help window. On top of that, it is very hard to carry out testing if we were to use WebEngine because there are many factors that have to be taken into account, such as individual network connectivity and their default browser etc.

Definitely understand your stance. I was also considering extracting just the command summary out instead of using the whole UG. I also agree that it feels like a wasted step to use the entire UG just to skip all the way to the command summary. The reason I decided to just copy the UG wholesale is that in this way, the work required to maintain the two files would be lower. This was the fork in the road:
1. To extract only the command summary out. On every update, the maintenance steps are updating UG to a newer version, AND extracting the command summary, then place it in /resources.
2. To just make an exact UG duplicate and paste it in /resources. The only maintenance step is to copy/paste the UG once. There is no need to manually extract the command summary.

I ultimately went with option 2, due to lesser involvement of manual work and therefore, in my opinion, more straightforward.

With regards to your other points, I agree with a table representation being neater. I am not sure how the table would turn out if any entry were to be too long, or if the window size were to be too small/large. With this in mind, I decided to go with simply printing text first (current approach), because this would at least produce a solution that is minimally functional. My intention was to switch away from webview ASAP, and replace it with a minimally functional help menu first. Following this, if I can get a tableview working well (without visual issues) before the deadline, I will definitely implement that.

**Comment by tanboonji** [comment]
> > I personally feel that there isn't a need to copy the whole `UserGuide.md` over. Here are some of my thoughts on the implementation:
> > 
> > 1. If we were to use the whole `UserGuide.md` and extract out only the command summary table, then I feel there isn't a point for the rest of the `UserGuide.md` to be copied over to resources.
> > 2. If we were to copy the whole `UserGuide.md`, would that mean that I would need to update the copy even though the command summary table is not updated?
> > 3. The help window only requires the command summary table, which would not be updated frequently unless there are implementation changes to commands. With that consideration, personally, I feel that hard coding the command summary table in the help window would suffice.
> > 4. It is possible to better format the command summary table in the help window? For example, to use a table, because the command summary table now is not very organised and hard to read.
> > 5. I would strongly suggest against using anything that has to deal with network connectivity and using the WebEngine to display the help window. On top of that, it is very hard to carry out testing if we were to use WebEngine because there are many factors that have to be taken into account, such as individual network connectivity and their default browser etc.
> 
> Definitely understand your stance. I was also considering extracting just the command summary out instead of using the whole UG. I also agree that it feels like a wasted step to use the entire UG just to skip all the way to the command summary. The reason I decided to just copy the UG wholesale is that in this way, the work required to maintain the two files would be lower. This was the fork in the road:
> 
> 1. To extract only the command summary out. On every update, the developer has to manually extract command summary.
> 2. To just make an exact UG duplicate. The only maintenance step is to copy/paste the UG. There is no need to manually extract the command summary.
> 
> I ultimately went with option 2, due to lesser involvement of manual work and therefore, in my opinion, more straightforward.
> 
> With regards to your other points, I agree with a table representation being neater. I am not sure how the table would turn out if any entry were to be too long, or if the window size were to be too small/large. With this in mind, I decided to go with simply printing text first (current approach), because this would at least produce a working solution that is minimally functional. My intention was to switch away from webview ASAP, and replace it with a minimally functional help menu first. Following this, if I can get a tableview working well (without visual issues) before the deadline, I will definitely implement that.

Regarding your first point, I think my implementation of hard coding the help window is slightly different from yours.

My idea of hard coding was to literally type out the command summary in either the `HelpWindow.fxml` or `HelpWindow.java`. The responsibility of updating the command information in the help window would then lie on the person creating/deleting/updating each individual command, similarly to how they will be required to update the command summary in the `UserGuide.md`, they would have to do so in the `HelpWindow.fxml` or `HelpWindow.java` as well.

Instead of having to update the `UserGuide.md` in the resources whenever the original `UserGuide.md` in the docs is updated, the command summary table would only be required to be updated when you create/delete/update each individual command.

**Comment by justgnohUG** [comment]
Based on what I'm seeing, I think I get what you are trying to do with duplicating the UserGuide.md. It seems to me that you are trying to somewhat automate the process, such that changes to UserGuide.md will be reflected in the `Help Window`. 

However, since you are duplicating the UserGuide.md, changes to the UserGuide will not reflect in the `Help Window`, unless the updated UserGuide.md is duplicated into `src/resources`, correct me if I'm wrong. 

Hence, I'd say that Boon Ji's suggestion for adding the command summary in `HelpWindow.fxml` or `HelpWindow.java` is what I'd second, too. 

I think it would make more sense however to update in `HelpWindow.java`, since `HelpWindow.fxml` is typically untouched for the most part.

**Comment by yaowei-soc** [comment]
If that is the case, I would prefer to have an implementation where we hard code the values into the text field/table with a table implementation being my preference

**Review by yaowei-soc — APPROVED** [review]
LGTM

**Review by justgnohUG — APPROVED** [review]
Resizing works. 

Triple Dot issue seems to be fixed. All triple dots are now uniform.

image

LGTM.

**Pull request merged**
