### PR TITLE
Change addressbook.json to a-bashbook.json

### LINKED ISSUE #232: Update addressbook.json to a-bashbook.json

### PR DESCRIPTION
**Pull request by justgnohUG**
Resolves #232 

I would like to raise some concerns and discuss some pointers.

1) Is it concerning to have a "-" within the file name? E.g `a-bashbook.json`

2) Is it better to consider CamelCase verison `ABashBook.json`? Or does having capitalisation possibly cause issues in the future?

3) Since CS2103T has some mention on Snake_Case I believe? Would it be a better choice to do something like `a_bashbook.json`?

### CODE REVIEW

**Review by darkdestry-t — APPROVED** [review]
1. Its fine. In fact its better to have a dash than a space
2. Possibly. If the file gets renamed with the same case. Which would probably be a problem caused by the user. (MacOS and Linux file paths)
3. Either one works. Neither is better.

**Comment by yaowei-soc** [comment]
What about renaming it to `abashbook.json` so that we don't have to deal with camecase?

**Comment by tanboonji** [comment]
I would go with `abashbook` so that is the same file name format as `aliasmap`.

**Comment by justgnohUG** [comment]
I have opted to go with `abashbook.json` for consistency reasons. And since there are no obvious pro's over one or the other.

**Review by yaowei-soc — APPROVED** [review]
LGTM

**Pull request merged**
