### PR TITLE
Fix invalid prefixes

### LINKED ISSUE #82: Incorrect parsing of field values for command prefixes that share the same front substring
eg. `add ... -p 12345 -pa456 ...`
The prefixes are `-p` and `-pa`, both share the same front substring of `-p`.
As such, the parsed value of  the `-p` field will be a456 (wrong), instead of 12345 (correct).

### PR DESCRIPTION
**Pull request by oeiyiping**
This is still currently work in progress.

Fixes #82

### CODE REVIEW

**Review by tanboonji — CHANGES_REQUESTED** [review]
There are issues with the `alias` command with the new implementation.

image

When parsing the arguments for the command to be aliased, the user input is trimmed, therefore the `-n` will not be recognised because whitespace is required after the prefix.

On another note, I have found out that the `AddressBookParser` is currently missing `filter` and `email` logic to handle `alias` command. Will be creating an issue and PR to solve this later. Do try to pull the new commits from the master branch because the `AddressBookParser` you are working on is currently outdated.

**Comment by oeiyiping** [comment]
> There are issues with the `alias` command with the new implementation.
> 
> image
> 
> The image above is from the the `ParserUtil.java`. When parsing the arguments for the command to be aliased, the user input is trimmed, therefore the `-n` will not be recognised because whitespace is required after the prefix.
> 
> On another note, I have found out that the `AddressBookParser` is currently missing `filter` and `email` logic to handle `alias` command. Will be creating an issue and PR to solve this later. Do try to pull the new commits from the master branch because the `AddressBookParser` you are working on is currently outdated.

Not sure if this issue is resulting from involving filter command. I cannot replicate this with other commands eg. alias add.
image
image
image

Here are the screenshots of my attempt to replicate the issue using alias add.

**Comment by tanboonji** [comment]
image

image

image

I am currently having an issue when running the following command: `alias add z add -n`

The preamble for the `ArgumentMultiMap` when parsing the command for aliasing seems to have some issues (not empty).

**Review by tanboonji — CHANGES_REQUESTED** [review]
image

image

image

There are still issues with aliasing `tag` command. The preamble is picking up `-t` in it as the index for tag command. This is because of the `.trim()` which is called on the user input in the `TagCommandParser.java`.

image

**Comment by tanboonji** [comment]
Other commands facing the same issue:
- `alias add q edit shown -n`
- `alias add q edit selected -n`

**Comment by tanboonji** [comment]
PR closed as the issue is solved with another PR.

**Pull request closed without merging**
