### PR TITLE
Improve code quality for code related to alias

### LINKED ISSUE #215: Improve code quality for code related to alias
- Remove redundant ObservableList in UniqueAliasMap
- Rename the term `aliases` in code to `aliasMap` and `commandAlias`

### PR DESCRIPTION
**Pull request by tanboonji**
- Remove redundant ObservableList in UniqueAliasMap
- Rename the term aliases in code to aliasMap and commandAlias

Closes #215

### CODE REVIEW

**Review by yaowei-soc — APPROVED** [review]
Most changes are name changes. LGTM.

**Review by oeiyiping — APPROVED** [review]
LGTM.

**Review by darkdestry-t — CHANGES_REQUESTED** [review]
DG not updated
image

**Review by darkdestry-t — APPROVED** [review]
LGTM

**Pull request merged**
