### PR TITLE
docs: fix UG based on PED issues

### LINKED ISSUE #165: [PE-D] User guide quick start has outdated example
Example given for adding a person is outdated and does not work.

Screenshot of error message: 

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: laurenlhy/ped#1

### LINKED ISSUE #167: [PE-D] User guide 'add' example given is incorrect
This example "Betsy Crower..." was given in the User Guide: 

Output: 

I believe this is caused by 'tag' not allowing spaces.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: laurenlhy/ped#3

### LINKED ISSUE #198: [PE-D] Adding person failed using the instructions given
#### Issue description
Following the instruction given in the user guide, the example
`add -n John Doe -p 98765432 -e johnd@example.com -a John street, block 123, #01-01`, fails in the application.

#### Steps to reproduce the issue

1. Launch the app 
2. `add -n John Doe -p 98765432 -e johnd@example.com -a John street, block 123, #01-01`

#### What's the expected result?

- Success

#### What's the actual result?

- Fail

#### Additional details / screenshot

- 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Cheng20010201/ped#1

### LINKED ISSUE #200: [PE-D] Example in the user guide does not work
#### Issue description
The second example in the `add` section does not work.

#### Steps to reproduce the issue

1.  Launch the application
2. `add -n Betsy Crowe -p 1234567 -e betsycrowe@example.com -c Amazon -j Manager -a Betsy Avenue -t Recruiter -t Intern Manager`

#### What's the expected result?

- Success, as advertised in the user guide

#### What's the actual result?

- Fail, "Tag names should be alphanumeric"

#### Additional details / screenshot

-------------
Labels: `severity.High` `type.DocumentationBug`
original: Cheng20010201/ped#3

### LINKED ISSUE #201: [PE-D] Third example of user guide 'add' section does not work
Similar to previous issue #3

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Cheng20010201/ped#4

### PR DESCRIPTION
**Pull request by oeiyiping**
Fixes #201
Fixes #200
Fixes #198
Fixes #167
Fixes #165

### CODE REVIEW

**Review by tanboonji — CHANGES_REQUESTED** [review]
The example in the command summary is still invalid. Other than that, LGTM.

**Review by yaowei-soc — APPROVED** [review]
LGTM

**Comment by oeiyiping** [comment]
> The example in the command summary is still invalid. Other than that, LGTM.

Fixed it in the latest commit, please 

> The example in the command summary is still invalid. Other than that, LGTM.

Fixed it in 99da815effef3129a54f2c7371a33806f57220e2.

**Review by tanboonji — APPROVED** [review]
LGTM.

**Pull request merged**
