### PR TITLE
Fix command output for empty person list

### LINKED ISSUE #242: Commands return success message for empty person list
Multiple instances where executing a command returns a success message even though the person list is empty (e.g. `clear`ed)

| Command                  | Message                      |
| ------------------------ | ---------------------------- |
| `edit shown -p 99998888` | Edited 0 person              |
| `delete shown`           | Deleted multiple persons:    |
| `select shown`           | Selected all shown person(s) |
| `email shown`            | URL Exception occurred       |

### PR DESCRIPTION
**Pull request by yaowei-soc**
Closes #242 

When applying these commands on an empty list, this will be the revised output.

| Command                     | Previous                                 | New                    |
| --------------------------- | ---------------------------------------- | ---------------------- |
| `edit 1 2 -p 99998888`      | The person index(es) provided is invalid | No person(s) to edit   |
| `edit selected -p 99998888` | No selected person to edit.              | No person(s) to edit   |
| `edit shown -p 99998888`    | Edited 0 person                          | No person(s) to edit   |
| `delete 1 2`                | The person index(es) provided is invalid | No person(s) to delete |
| `delete selected`           | No selected person to delete.            | No person(s) to delete |
| `delete shown`              | Deleted multiple persons:                | No person(s) to delete |
| `select 1 2`                | The person index(es) provided is invalid | No person(s) to select |
| `select shown`              | Selected all shown person(s)             | No person(s) to select |
| `email 1 2`                 | The person index(es) provided is invalid | No person(s) to email  |
| `email selected`            | No selected person to email.             | No person(s) to email  |
| `email shown`               | URL Exception occurred                   | No person(s) to email  |

When executing on a valid person list, this will be the revised output:

| Command                     | Message                       |
| --------------------------- | ----------------------------- |
| `edit 1 -p 99998888`        | Edited person                 |
| `edit 1 2 -p 99998888`      | Edited 2 person(s)            |
| `edit selected -p 99998888` | No selected person(s) to edit |
| `delete 1`                  | Deleted person                |
| `delete 1 2`                | Deleted multiple person(s)    |
| `delete selected`           | Deleted multiple person(s):   |
| `delete shown`              | Deleted multiple person(s):   |
| `select 1 2`                | Selected person(s)            |
| `select shown`              | Selected all shown person(s)  |
| `email 1 2`                 | Opened email client           |
| `email selected`            | Opened email client           |
| `email shown`               | Opened email client           |

### CODE REVIEW

**Review by tanboonji — APPROVED** [review]
LGTM

**Review by oeiyiping — COMMENTED** [review]
image
Minor grammar issue: person is returned even though >1 persons are edited.

**Comment by yaowei-soc** [comment]
@oeiyiping Updated messages with the following success scenario

| Command                     | Message                       |
| --------------------------- | ----------------------------- |
| `edit 1 -p 99998888`        | Edited person                 |
| `edit 1 2 -p 99998888`      | Edited 2 person(s)            |
| `edit selected -p 99998888` | No selected person(s) to edit |
| `delete 1`                  | Deleted person                |
| `delete 1 2`                | Deleted multiple person(s)    |
| `delete selected`           | Deleted multiple person(s):   |
| `delete shown`              | Deleted multiple person(s):   |
| `select 1 2`                | Selected person(s)            |
| `select shown`              | Selected all shown person(s)  |
| `email 1 2`                 | Opened email client           |
| `email selected`            | Opened email client           |
| `email shown`               | Opened email client           |

**Review by oeiyiping — APPROVED** [review]
LGTM.

**Pull request merged**
